#ifndef _TOKENS_H_
#define _TOKENS_H_

typedef enum {
  BEG, END, DOT, CONST, EQ, SEMI_COL, TYPE,
  VAR, COLON, ARRAY, COMMA, OF, POINTER, TO,
  ASSIGN, LPAR, RPAR, IF, THEN, ELSIF, ELSE,
  WHILE, DO, EXIT, RETURN, PLUS, MINUS, NIL,
  INT, REAL, CHAR, NEQ, LT, LE, GT, GE, IS,
  OR, TIMES, SLASH, DIV, MOD, AMP, LBRA, RBRA,
  HAT, IDENT, TRUE, FALSE
} token_t;

#endif /* _TOKENS_H_ */
